idf_component_register(
    SRCS
        "src/main.c"
        "src/lvgl_gui.c"
        "src/touch.c"
        "src/lcd.c"
        "src/api.c"
        "src/sleep.c"    
        "images/logo_pwr_pl.c"
        "images/logo_pwr_eng.c"
        "images/flag_pl.c"
        "images/flag_eng.c"
        "fonts/lv_font_aptos_20.c"
        "fonts/lv_font_aptos_22.c"
        "fonts/lv_font_aptos_light_17.c"
        "fonts/lv_font_aptos_light_25.c"
        "fonts/lv_font_aptos_semibold_22.c"   
    INCLUDE_DIRS
        "."
        "inc"
    REQUIRES
        esp_wifi
        esp_event
        esp_timer
        esp_http_client
        json
        nvs_flash
        mbedtls
        spiffs
)